/* automatically generated by rust-bindgen 0.59.2 */

extern "C" {
    #[doc = " Returns the version string for libmongocrypt."]
    #[doc = ""]
    #[doc = " @param[out] len  An optional length of the returned string. May be NULL."]
    #[doc = " @returns a NULL terminated version string for libmongocrypt."]
    pub fn mongocrypt_version(len: *mut u32) -> *const ::std::os::raw::c_char;
}
